name: proapps_mobile
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^6.5.7
  google_fonts: ^4.0.3
  flutter_hooks: ^0.18.6
  url_strategy: ^0.2.0
  shimmer_animation: ^2.1.0+1
  loading_animation_widget: ^1.2.0+4
  lottie: ^2.3.2
  http: ^0.13.5
  result_type: ^0.2.0
  dropdown_search: ^5.0.6
  flutter_launcher_icons: ^0.13.1
  path: ^1.8.3
  path_provider: ^2.0.15
  intl: ^0.18.1
  camera: ^0.10.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  test: ^1.22.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/
    - assets/logo/
    - assets/animations/
    - assets/icons/
  